version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.14

parameters:
  dev-alerts-slack-channel:
    type: string
    default: interventions-dev-notifications
  dev-releases-slack-channel:
    type: string
    default: interventions-dev-notifications
  releases-slack-channel:
    type: string
    default: interventions

jobs:
  validate:
    executor:
      name: hmpps/java_postgres
      jdk_tag: "17.0"
      postgres_tag: "14-alpine"
      postgres_username: postgres
      postgres_password: password
      postgres_db: onboarding_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - validate
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.dev-releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-interventions-preprod-deploy
          requires:
            - deploy_dev
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-interventions-prod-deploy
          requires:
            - request-prod-approval

  security:
    triggers:
      - schedule:
          cron: "18 6 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          slack_channel: << pipeline.parameters.dev-alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          slack_channel: << pipeline.parameters.dev-alerts-slack-channel >>
          context:
            - hmpps-common-vars
      - hmpps/veracode_pipeline_scan:
          slack_channel: << pipeline.parameters.dev-alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
  security-weekly:
    triggers:
      - schedule:
          cron: "35 6 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/veracode_policy_scan:
          slack_channel: << pipeline.parameters.dev-alerts-slack-channel >>
          context:
            - veracode-credentials
            - hmpps-common-vars
